name: meme_generator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.2.3 # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stream_bloc: ^0.5.3
  freezed_annotation: ^2.4.1
  local_database:
    path: packages/local_database
  meta: ^1.10.0
  image_picker: ^1.0.7
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.4.7
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
